// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: surgalt/v1/surgalt.proto

// surgalt.mn — gRPC + Protobuf API.
// Нэг handler гурван протоколоор үйлчилнэ (Connect): gRPC (мобайл, сервис), gRPC-Web, Connect-JSON
// (хөтөч энгийн fetch-ээр: POST /surgalt.v1.Surgalt/<Method>, Content-Type: application/json).
// Токен: header "Authorization: Bearer <token>".

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Surgalt_GetTeacher_FullMethodName   = "/surgalt.v1.Surgalt/GetTeacher"
	Surgalt_GetCourse_FullMethodName    = "/surgalt.v1.Surgalt/GetCourse"
	Surgalt_Search_FullMethodName       = "/surgalt.v1.Surgalt/Search"
	Surgalt_Me_FullMethodName           = "/surgalt.v1.Surgalt/Me"
	Surgalt_StartSession_FullMethodName = "/surgalt.v1.Surgalt/StartSession"
	Surgalt_Beat_FullMethodName         = "/surgalt.v1.Surgalt/Beat"
	Surgalt_BeatOnce_FullMethodName     = "/surgalt.v1.Surgalt/BeatOnce"
	Surgalt_GetAnalytics_FullMethodName = "/surgalt.v1.Surgalt/GetAnalytics"
)

// SurgaltClient is the client API for Surgalt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SurgaltClient interface {
	// ---- нээлттэй ----
	GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...grpc.CallOption) (*TeacherProfile, error)
	GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*CourseDetail, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// ---- нэвтэрсэн хэрэглэгч ----
	Me(ctx context.Context, in *MeRequest, opts ...grpc.CallOption) (*User, error)
	// Хичээл үзэх идэвхийн сесс нээнэ (хяналтын бодлого, усан тэмдэг буцаана).
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// Клиент урсгалаар 15 секунд тутмын идэвхийн тайлан илгээнэ; сервер нийт идэвхтэй секундийг буцаана.
	Beat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BeatRequest, BeatResponse], error)
	// Нэг удаагийн тайлан (хөтөч: fetch-ээр, урсгалгүй).
	BeatOnce(ctx context.Context, in *BeatRequest, opts ...grpc.CallOption) (*BeatResponse, error)
	// ---- багш ----
	GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
}

type surgaltClient struct {
	cc grpc.ClientConnInterface
}

func NewSurgaltClient(cc grpc.ClientConnInterface) SurgaltClient {
	return &surgaltClient{cc}
}

func (c *surgaltClient) GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...grpc.CallOption) (*TeacherProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherProfile)
	err := c.cc.Invoke(ctx, Surgalt_GetTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surgaltClient) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*CourseDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseDetail)
	err := c.cc.Invoke(ctx, Surgalt_GetCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surgaltClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Surgalt_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surgaltClient) Me(ctx context.Context, in *MeRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, Surgalt_Me_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surgaltClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, Surgalt_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surgaltClient) Beat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BeatRequest, BeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Surgalt_ServiceDesc.Streams[0], Surgalt_Beat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeatRequest, BeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Surgalt_BeatClient = grpc.BidiStreamingClient[BeatRequest, BeatResponse]

func (c *surgaltClient) BeatOnce(ctx context.Context, in *BeatRequest, opts ...grpc.CallOption) (*BeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeatResponse)
	err := c.cc.Invoke(ctx, Surgalt_BeatOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surgaltClient) GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsResponse)
	err := c.cc.Invoke(ctx, Surgalt_GetAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurgaltServer is the server API for Surgalt service.
// All implementations must embed UnimplementedSurgaltServer
// for forward compatibility.
type SurgaltServer interface {
	// ---- нээлттэй ----
	GetTeacher(context.Context, *GetTeacherRequest) (*TeacherProfile, error)
	GetCourse(context.Context, *GetCourseRequest) (*CourseDetail, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// ---- нэвтэрсэн хэрэглэгч ----
	Me(context.Context, *MeRequest) (*User, error)
	// Хичээл үзэх идэвхийн сесс нээнэ (хяналтын бодлого, усан тэмдэг буцаана).
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// Клиент урсгалаар 15 секунд тутмын идэвхийн тайлан илгээнэ; сервер нийт идэвхтэй секундийг буцаана.
	Beat(grpc.BidiStreamingServer[BeatRequest, BeatResponse]) error
	// Нэг удаагийн тайлан (хөтөч: fetch-ээр, урсгалгүй).
	BeatOnce(context.Context, *BeatRequest) (*BeatResponse, error)
	// ---- багш ----
	GetAnalytics(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error)
	mustEmbedUnimplementedSurgaltServer()
}

// UnimplementedSurgaltServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSurgaltServer struct{}

func (UnimplementedSurgaltServer) GetTeacher(context.Context, *GetTeacherRequest) (*TeacherProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacher not implemented")
}
func (UnimplementedSurgaltServer) GetCourse(context.Context, *GetCourseRequest) (*CourseDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedSurgaltServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSurgaltServer) Me(context.Context, *MeRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method Me not implemented")
}
func (UnimplementedSurgaltServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedSurgaltServer) Beat(grpc.BidiStreamingServer[BeatRequest, BeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Beat not implemented")
}
func (UnimplementedSurgaltServer) BeatOnce(context.Context, *BeatRequest) (*BeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeatOnce not implemented")
}
func (UnimplementedSurgaltServer) GetAnalytics(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalytics not implemented")
}
func (UnimplementedSurgaltServer) mustEmbedUnimplementedSurgaltServer() {}
func (UnimplementedSurgaltServer) testEmbeddedByValue()                 {}

// UnsafeSurgaltServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SurgaltServer will
// result in compilation errors.
type UnsafeSurgaltServer interface {
	mustEmbedUnimplementedSurgaltServer()
}

func RegisterSurgaltServer(s grpc.ServiceRegistrar, srv SurgaltServer) {
	// If the following call panics, it indicates UnimplementedSurgaltServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Surgalt_ServiceDesc, srv)
}

func _Surgalt_GetTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).GetTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_GetTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).GetTeacher(ctx, req.(*GetTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surgalt_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_GetCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).GetCourse(ctx, req.(*GetCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surgalt_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surgalt_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_Me_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).Me(ctx, req.(*MeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surgalt_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surgalt_Beat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SurgaltServer).Beat(&grpc.GenericServerStream[BeatRequest, BeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Surgalt_BeatServer = grpc.BidiStreamingServer[BeatRequest, BeatResponse]

func _Surgalt_BeatOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).BeatOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_BeatOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).BeatOnce(ctx, req.(*BeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surgalt_GetAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurgaltServer).GetAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surgalt_GetAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurgaltServer).GetAnalytics(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Surgalt_ServiceDesc is the grpc.ServiceDesc for Surgalt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Surgalt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surgalt.v1.Surgalt",
	HandlerType: (*SurgaltServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeacher",
			Handler:    _Surgalt_GetTeacher_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _Surgalt_GetCourse_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Surgalt_Search_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _Surgalt_Me_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _Surgalt_StartSession_Handler,
		},
		{
			MethodName: "BeatOnce",
			Handler:    _Surgalt_BeatOnce_Handler,
		},
		{
			MethodName: "GetAnalytics",
			Handler:    _Surgalt_GetAnalytics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Beat",
			Handler:       _Surgalt_Beat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "surgalt/v1/surgalt.proto",
}
