// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: surgalt/v1/surgalt.proto

// surgalt.mn — gRPC + Protobuf API.
// Нэг handler гурван протоколоор үйлчилнэ (Connect): gRPC (мобайл, сервис), gRPC-Web, Connect-JSON
// (хөтөч энгийн fetch-ээр: POST /surgalt.v1.Surgalt/<Method>, Content-Type: application/json).
// Токен: header "Authorization: Bearer <token>".

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherRequest) Reset() {
	*x = GetTeacherRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherRequest) ProtoMessage() {}

func (x *GetTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{0}
}

func (x *GetTeacherRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Link) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Teacher struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Headline        string                 `protobuf:"bytes,4,opt,name=headline,proto3" json:"headline,omitempty"`
	Bio             string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CoverUrl        string                 `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Subjects        []string               `protobuf:"bytes,8,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Location        string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Links           []*Link                `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	JoinedYear      int32                  `protobuf:"varint,11,opt,name=joined_year,json=joinedYear,proto3" json:"joined_year,omitempty"`
	StudentCount    int64                  `protobuf:"varint,12,opt,name=student_count,json=studentCount,proto3" json:"student_count,omitempty"`
	CourseCount     int32                  `protobuf:"varint,13,opt,name=course_count,json=courseCount,proto3" json:"course_count,omitempty"`
	LessonCount     int32                  `protobuf:"varint,14,opt,name=lesson_count,json=lessonCount,proto3" json:"lesson_count,omitempty"`
	FreeLessonCount int32                  `protobuf:"varint,15,opt,name=free_lesson_count,json=freeLessonCount,proto3" json:"free_lesson_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{2}
}

func (x *Teacher) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Teacher) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Teacher) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Teacher) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *Teacher) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Teacher) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Teacher) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Teacher) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Teacher) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Teacher) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Teacher) GetJoinedYear() int32 {
	if x != nil {
		return x.JoinedYear
	}
	return 0
}

func (x *Teacher) GetStudentCount() int64 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

func (x *Teacher) GetCourseCount() int32 {
	if x != nil {
		return x.CourseCount
	}
	return 0
}

func (x *Teacher) GetLessonCount() int32 {
	if x != nil {
		return x.LessonCount
	}
	return 0
}

func (x *Teacher) GetFreeLessonCount() int32 {
	if x != nil {
		return x.FreeLessonCount
	}
	return 0
}

type Course struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeacherId       string                 `protobuf:"bytes,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price           int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Published       bool                   `protobuf:"varint,6,opt,name=published,proto3" json:"published,omitempty"`
	Drip            bool                   `protobuf:"varint,7,opt,name=drip,proto3" json:"drip,omitempty"`
	UnlockAllPaid   bool                   `protobuf:"varint,8,opt,name=unlock_all_paid,json=unlockAllPaid,proto3" json:"unlock_all_paid,omitempty"`
	Camera          string                 `protobuf:"bytes,9,opt,name=camera,proto3" json:"camera,omitempty"`
	Certificate     bool                   `protobuf:"varint,10,opt,name=certificate,proto3" json:"certificate,omitempty"`
	LessonCount     int32                  `protobuf:"varint,11,opt,name=lesson_count,json=lessonCount,proto3" json:"lesson_count,omitempty"`
	FreeLessonCount int32                  `protobuf:"varint,12,opt,name=free_lesson_count,json=freeLessonCount,proto3" json:"free_lesson_count,omitempty"`
	Views           int64                  `protobuf:"varint,13,opt,name=views,proto3" json:"views,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,14,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{3}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Course) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *Course) GetDrip() bool {
	if x != nil {
		return x.Drip
	}
	return false
}

func (x *Course) GetUnlockAllPaid() bool {
	if x != nil {
		return x.UnlockAllPaid
	}
	return false
}

func (x *Course) GetCamera() string {
	if x != nil {
		return x.Camera
	}
	return ""
}

func (x *Course) GetCertificate() bool {
	if x != nil {
		return x.Certificate
	}
	return false
}

func (x *Course) GetLessonCount() int32 {
	if x != nil {
		return x.LessonCount
	}
	return 0
}

func (x *Course) GetFreeLessonCount() int32 {
	if x != nil {
		return x.FreeLessonCount
	}
	return 0
}

func (x *Course) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Course) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type TeacherProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teacher       *Teacher               `protobuf:"bytes,1,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Courses       []*Course              `protobuf:"bytes,2,rep,name=courses,proto3" json:"courses,omitempty"`
	TopCourseId   string                 `protobuf:"bytes,3,opt,name=top_course_id,json=topCourseId,proto3" json:"top_course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherProfile) Reset() {
	*x = TeacherProfile{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherProfile) ProtoMessage() {}

func (x *TeacherProfile) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherProfile.ProtoReflect.Descriptor instead.
func (*TeacherProfile) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{4}
}

func (x *TeacherProfile) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *TeacherProfile) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *TeacherProfile) GetTopCourseId() string {
	if x != nil {
		return x.TopCourseId
	}
	return ""
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{5}
}

func (x *GetCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IsFree        bool                   `protobuf:"varint,3,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	UnlockAfterH  int32                  `protobuf:"varint,6,opt,name=unlock_after_h,json=unlockAfterH,proto3" json:"unlock_after_h,omitempty"`
	AlwaysOpen    bool                   `protobuf:"varint,7,opt,name=always_open,json=alwaysOpen,proto3" json:"always_open,omitempty"`
	Format        string                 `protobuf:"bytes,8,opt,name=format,proto3" json:"format,omitempty"`
	Mode          string                 `protobuf:"bytes,9,opt,name=mode,proto3" json:"mode,omitempty"`
	Section       string                 `protobuf:"bytes,10,opt,name=section,proto3" json:"section,omitempty"`
	ActiveMin     int32                  `protobuf:"varint,11,opt,name=active_min,json=activeMin,proto3" json:"active_min,omitempty"`
	Exam          bool                   `protobuf:"varint,12,opt,name=exam,proto3" json:"exam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{6}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *Lesson) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Lesson) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Lesson) GetUnlockAfterH() int32 {
	if x != nil {
		return x.UnlockAfterH
	}
	return 0
}

func (x *Lesson) GetAlwaysOpen() bool {
	if x != nil {
		return x.AlwaysOpen
	}
	return false
}

func (x *Lesson) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Lesson) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Lesson) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Lesson) GetActiveMin() int32 {
	if x != nil {
		return x.ActiveMin
	}
	return 0
}

func (x *Lesson) GetExam() bool {
	if x != nil {
		return x.Exam
	}
	return false
}

type CourseDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Teacher       *Teacher               `protobuf:"bytes,2,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Lessons       []*Lesson              `protobuf:"bytes,3,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetail) Reset() {
	*x = CourseDetail{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetail) ProtoMessage() {}

func (x *CourseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetail.ProtoReflect.Descriptor instead.
func (*CourseDetail) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{7}
}

func (x *CourseDetail) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *CourseDetail) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *CourseDetail) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"` // free | paid | cert | exam | ""
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{8}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Teacher       *Teacher               `protobuf:"bytes,3,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Lessons       int32                  `protobuf:"varint,5,opt,name=lessons,proto3" json:"lessons,omitempty"`
	FreeLessons   int32                  `protobuf:"varint,6,opt,name=free_lessons,json=freeLessons,proto3" json:"free_lessons,omitempty"`
	Views         int64                  `protobuf:"varint,7,opt,name=views,proto3" json:"views,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Match         string                 `protobuf:"bytes,9,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{9}
}

func (x *SearchHit) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *SearchHit) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SearchHit) GetLessons() int32 {
	if x != nil {
		return x.Lessons
	}
	return 0
}

func (x *SearchHit) GetFreeLessons() int32 {
	if x != nil {
		return x.FreeLessons
	}
	return 0
}

func (x *SearchHit) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *SearchHit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchHit) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchHit           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	PerPage       int32                  `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResponse) GetItems() []*SearchHit {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *SearchResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{11}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // lesson | exam
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{13}
}

func (x *StartSessionRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *StartSessionRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *StartSessionRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Watermark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Watermark) Reset() {
	*x = Watermark{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Watermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watermark) ProtoMessage() {}

func (x *Watermark) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watermark.ProtoReflect.Descriptor instead.
func (*Watermark) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{14}
}

func (x *Watermark) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Watermark) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Watermark) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camera        string                 `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
	PingSec       int32                  `protobuf:"varint,2,opt,name=ping_sec,json=pingSec,proto3" json:"ping_sec,omitempty"`
	PingAnswerSec int32                  `protobuf:"varint,3,opt,name=ping_answer_sec,json=pingAnswerSec,proto3" json:"ping_answer_sec,omitempty"`
	IdleSec       int32                  `protobuf:"varint,4,opt,name=idle_sec,json=idleSec,proto3" json:"idle_sec,omitempty"`
	BeatSec       int32                  `protobuf:"varint,5,opt,name=beat_sec,json=beatSec,proto3" json:"beat_sec,omitempty"`
	ActiveMin     int32                  `protobuf:"varint,6,opt,name=active_min,json=activeMin,proto3" json:"active_min,omitempty"`
	ActiveDoneSec int32                  `protobuf:"varint,7,opt,name=active_done_sec,json=activeDoneSec,proto3" json:"active_done_sec,omitempty"`
	Owner         bool                   `protobuf:"varint,8,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{15}
}

func (x *Policy) GetCamera() string {
	if x != nil {
		return x.Camera
	}
	return ""
}

func (x *Policy) GetPingSec() int32 {
	if x != nil {
		return x.PingSec
	}
	return 0
}

func (x *Policy) GetPingAnswerSec() int32 {
	if x != nil {
		return x.PingAnswerSec
	}
	return 0
}

func (x *Policy) GetIdleSec() int32 {
	if x != nil {
		return x.IdleSec
	}
	return 0
}

func (x *Policy) GetBeatSec() int32 {
	if x != nil {
		return x.BeatSec
	}
	return 0
}

func (x *Policy) GetActiveMin() int32 {
	if x != nil {
		return x.ActiveMin
	}
	return 0
}

func (x *Policy) GetActiveDoneSec() int32 {
	if x != nil {
		return x.ActiveDoneSec
	}
	return 0
}

func (x *Policy) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Watermark     *Watermark             `protobuf:"bytes,2,opt,name=watermark,proto3" json:"watermark,omitempty"`
	Policy        *Policy                `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{16}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetWatermark() *Watermark {
	if x != nil {
		return x.Watermark
	}
	return nil
}

func (x *StartSessionResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type BeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatEvent) Reset() {
	*x = BeatEvent{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatEvent) ProtoMessage() {}

func (x *BeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatEvent.ProtoReflect.Descriptor instead.
func (*BeatEvent) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{17}
}

func (x *BeatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BeatEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type BeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Active        int32                  `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Idle          int32                  `protobuf:"varint,3,opt,name=idle,proto3" json:"idle,omitempty"`
	Away          int32                  `protobuf:"varint,4,opt,name=away,proto3" json:"away,omitempty"`
	FocusSum      float64                `protobuf:"fixed64,5,opt,name=focus_sum,json=focusSum,proto3" json:"focus_sum,omitempty"`
	FocusN        int32                  `protobuf:"varint,6,opt,name=focus_n,json=focusN,proto3" json:"focus_n,omitempty"`
	Camera        bool                   `protobuf:"varint,7,opt,name=camera,proto3" json:"camera,omitempty"`
	AttemptId     string                 `protobuf:"bytes,8,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	End           string                 `protobuf:"bytes,9,opt,name=end,proto3" json:"end,omitempty"`
	Events        []*BeatEvent           `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatRequest) Reset() {
	*x = BeatRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatRequest) ProtoMessage() {}

func (x *BeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatRequest.ProtoReflect.Descriptor instead.
func (*BeatRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{18}
}

func (x *BeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BeatRequest) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *BeatRequest) GetIdle() int32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *BeatRequest) GetAway() int32 {
	if x != nil {
		return x.Away
	}
	return 0
}

func (x *BeatRequest) GetFocusSum() float64 {
	if x != nil {
		return x.FocusSum
	}
	return 0
}

func (x *BeatRequest) GetFocusN() int32 {
	if x != nil {
		return x.FocusN
	}
	return 0
}

func (x *BeatRequest) GetCamera() bool {
	if x != nil {
		return x.Camera
	}
	return false
}

func (x *BeatRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *BeatRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *BeatRequest) GetEvents() []*BeatEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type BeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ActiveDoneSec int32                  `protobuf:"varint,2,opt,name=active_done_sec,json=activeDoneSec,proto3" json:"active_done_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatResponse) Reset() {
	*x = BeatResponse{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatResponse) ProtoMessage() {}

func (x *BeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatResponse.ProtoReflect.Descriptor instead.
func (*BeatResponse) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{19}
}

func (x *BeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BeatResponse) GetActiveDoneSec() int32 {
	if x != nil {
		return x.ActiveDoneSec
	}
	return 0
}

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"` // хоосон = бүх сургалт
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`                        // 0 = 30
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{20}
}

func (x *AnalyticsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AnalyticsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type StudentStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sessions      int32                  `protobuf:"varint,3,opt,name=sessions,proto3" json:"sessions,omitempty"`
	TotalSec      int32                  `protobuf:"varint,4,opt,name=total_sec,json=totalSec,proto3" json:"total_sec,omitempty"`
	ActiveSec     int32                  `protobuf:"varint,5,opt,name=active_sec,json=activeSec,proto3" json:"active_sec,omitempty"`
	ActivePct     int32                  `protobuf:"varint,6,opt,name=active_pct,json=activePct,proto3" json:"active_pct,omitempty"`
	Attention     int32                  `protobuf:"varint,7,opt,name=attention,proto3" json:"attention,omitempty"`
	Violations    int32                  `protobuf:"varint,8,opt,name=violations,proto3" json:"violations,omitempty"`
	Lessons       int32                  `protobuf:"varint,9,opt,name=lessons,proto3" json:"lessons,omitempty"`
	ExamBest      int32                  `protobuf:"varint,10,opt,name=exam_best,json=examBest,proto3" json:"exam_best,omitempty"`
	QuizAccuracy  int32                  `protobuf:"varint,11,opt,name=quiz_accuracy,json=quizAccuracy,proto3" json:"quiz_accuracy,omitempty"`
	QuizTotal     int32                  `protobuf:"varint,12,opt,name=quiz_total,json=quizTotal,proto3" json:"quiz_total,omitempty"`
	Reflections   int32                  `protobuf:"varint,13,opt,name=reflections,proto3" json:"reflections,omitempty"`
	VideoCoverage int32                  `protobuf:"varint,14,opt,name=video_coverage,json=videoCoverage,proto3" json:"video_coverage,omitempty"`
	StreakDays    int32                  `protobuf:"varint,15,opt,name=streak_days,json=streakDays,proto3" json:"streak_days,omitempty"`
	LearnScore    int32                  `protobuf:"varint,16,opt,name=learn_score,json=learnScore,proto3" json:"learn_score,omitempty"`
	Risk          string                 `protobuf:"bytes,17,opt,name=risk,proto3" json:"risk,omitempty"`
	LastAtUnix    int64                  `protobuf:"varint,18,opt,name=last_at_unix,json=lastAtUnix,proto3" json:"last_at_unix,omitempty"`
	Counts        map[string]int32       `protobuf:"bytes,19,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentStat) Reset() {
	*x = StudentStat{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentStat) ProtoMessage() {}

func (x *StudentStat) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentStat.ProtoReflect.Descriptor instead.
func (*StudentStat) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{21}
}

func (x *StudentStat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StudentStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentStat) GetSessions() int32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

func (x *StudentStat) GetTotalSec() int32 {
	if x != nil {
		return x.TotalSec
	}
	return 0
}

func (x *StudentStat) GetActiveSec() int32 {
	if x != nil {
		return x.ActiveSec
	}
	return 0
}

func (x *StudentStat) GetActivePct() int32 {
	if x != nil {
		return x.ActivePct
	}
	return 0
}

func (x *StudentStat) GetAttention() int32 {
	if x != nil {
		return x.Attention
	}
	return 0
}

func (x *StudentStat) GetViolations() int32 {
	if x != nil {
		return x.Violations
	}
	return 0
}

func (x *StudentStat) GetLessons() int32 {
	if x != nil {
		return x.Lessons
	}
	return 0
}

func (x *StudentStat) GetExamBest() int32 {
	if x != nil {
		return x.ExamBest
	}
	return 0
}

func (x *StudentStat) GetQuizAccuracy() int32 {
	if x != nil {
		return x.QuizAccuracy
	}
	return 0
}

func (x *StudentStat) GetQuizTotal() int32 {
	if x != nil {
		return x.QuizTotal
	}
	return 0
}

func (x *StudentStat) GetReflections() int32 {
	if x != nil {
		return x.Reflections
	}
	return 0
}

func (x *StudentStat) GetVideoCoverage() int32 {
	if x != nil {
		return x.VideoCoverage
	}
	return 0
}

func (x *StudentStat) GetStreakDays() int32 {
	if x != nil {
		return x.StreakDays
	}
	return 0
}

func (x *StudentStat) GetLearnScore() int32 {
	if x != nil {
		return x.LearnScore
	}
	return 0
}

func (x *StudentStat) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

func (x *StudentStat) GetLastAtUnix() int64 {
	if x != nil {
		return x.LastAtUnix
	}
	return 0
}

func (x *StudentStat) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type DailyActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	ActiveSec     int32                  `protobuf:"varint,2,opt,name=active_sec,json=activeSec,proto3" json:"active_sec,omitempty"`
	InactiveSec   int32                  `protobuf:"varint,3,opt,name=inactive_sec,json=inactiveSec,proto3" json:"inactive_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyActivity) Reset() {
	*x = DailyActivity{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyActivity) ProtoMessage() {}

func (x *DailyActivity) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyActivity.ProtoReflect.Descriptor instead.
func (*DailyActivity) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{22}
}

func (x *DailyActivity) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DailyActivity) GetActiveSec() int32 {
	if x != nil {
		return x.ActiveSec
	}
	return 0
}

func (x *DailyActivity) GetInactiveSec() int32 {
	if x != nil {
		return x.InactiveSec
	}
	return 0
}

type AnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentStat         `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	Daily         []*DailyActivity       `protobuf:"bytes,2,rep,name=daily,proto3" json:"daily,omitempty"`
	TotalStudents int32                  `protobuf:"varint,3,opt,name=total_students,json=totalStudents,proto3" json:"total_students,omitempty"`
	Live          int32                  `protobuf:"varint,4,opt,name=live,proto3" json:"live,omitempty"`
	ActivePct     int32                  `protobuf:"varint,5,opt,name=active_pct,json=activePct,proto3" json:"active_pct,omitempty"`
	Attention     int32                  `protobuf:"varint,6,opt,name=attention,proto3" json:"attention,omitempty"`
	Violations    int32                  `protobuf:"varint,7,opt,name=violations,proto3" json:"violations,omitempty"`
	LearnScore    int32                  `protobuf:"varint,8,opt,name=learn_score,json=learnScore,proto3" json:"learn_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surgalt_v1_surgalt_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_surgalt_v1_surgalt_proto_rawDescGZIP(), []int{23}
}

func (x *AnalyticsResponse) GetStudents() []*StudentStat {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *AnalyticsResponse) GetDaily() []*DailyActivity {
	if x != nil {
		return x.Daily
	}
	return nil
}

func (x *AnalyticsResponse) GetTotalStudents() int32 {
	if x != nil {
		return x.TotalStudents
	}
	return 0
}

func (x *AnalyticsResponse) GetLive() int32 {
	if x != nil {
		return x.Live
	}
	return 0
}

func (x *AnalyticsResponse) GetActivePct() int32 {
	if x != nil {
		return x.ActivePct
	}
	return 0
}

func (x *AnalyticsResponse) GetAttention() int32 {
	if x != nil {
		return x.Attention
	}
	return 0
}

func (x *AnalyticsResponse) GetViolations() int32 {
	if x != nil {
		return x.Violations
	}
	return 0
}

func (x *AnalyticsResponse) GetLearnScore() int32 {
	if x != nil {
		return x.LearnScore
	}
	return 0
}

var File_surgalt_v1_surgalt_proto protoreflect.FileDescriptor

const file_surgalt_v1_surgalt_proto_rawDesc = "" +
	"\n" +
	"\x18surgalt/v1/surgalt.proto\x12\n" +
	"surgalt.v1\"/\n" +
	"\x11GetTeacherRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"@\n" +
	"\x04Link\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xda\x03\n" +
	"\aTeacher\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bheadline\x18\x04 \x01(\tR\bheadline\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bsubjects\x18\b \x03(\tR\bsubjects\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12&\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x10.surgalt.v1.LinkR\x05links\x12\x1f\n" +
	"\vjoined_year\x18\v \x01(\x05R\n" +
	"joinedYear\x12#\n" +
	"\rstudent_count\x18\f \x01(\x03R\fstudentCount\x12!\n" +
	"\fcourse_count\x18\r \x01(\x05R\vcourseCount\x12!\n" +
	"\flesson_count\x18\x0e \x01(\x05R\vlessonCount\x12*\n" +
	"\x11free_lesson_count\x18\x0f \x01(\x05R\x0ffreeLessonCount\"\xa6\x03\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1c\n" +
	"\tpublished\x18\x06 \x01(\bR\tpublished\x12\x12\n" +
	"\x04drip\x18\a \x01(\bR\x04drip\x12&\n" +
	"\x0funlock_all_paid\x18\b \x01(\bR\runlockAllPaid\x12\x16\n" +
	"\x06camera\x18\t \x01(\tR\x06camera\x12 \n" +
	"\vcertificate\x18\n" +
	" \x01(\bR\vcertificate\x12!\n" +
	"\flesson_count\x18\v \x01(\x05R\vlessonCount\x12*\n" +
	"\x11free_lesson_count\x18\f \x01(\x05R\x0ffreeLessonCount\x12\x14\n" +
	"\x05views\x18\r \x01(\x03R\x05views\x12&\n" +
	"\x0fcreated_at_unix\x18\x0e \x01(\x03R\rcreatedAtUnix\"\x91\x01\n" +
	"\x0eTeacherProfile\x12-\n" +
	"\ateacher\x18\x01 \x01(\v2\x13.surgalt.v1.TeacherR\ateacher\x12,\n" +
	"\acourses\x18\x02 \x03(\v2\x12.surgalt.v1.CourseR\acourses\x12\"\n" +
	"\rtop_course_id\x18\x03 \x01(\tR\vtopCourseId\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb9\x02\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\ais_free\x18\x03 \x01(\bR\x06isFree\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12$\n" +
	"\x0eunlock_after_h\x18\x06 \x01(\x05R\funlockAfterH\x12\x1f\n" +
	"\valways_open\x18\a \x01(\bR\n" +
	"alwaysOpen\x12\x16\n" +
	"\x06format\x18\b \x01(\tR\x06format\x12\x12\n" +
	"\x04mode\x18\t \x01(\tR\x04mode\x12\x18\n" +
	"\asection\x18\n" +
	" \x01(\tR\asection\x12\x1d\n" +
	"\n" +
	"active_min\x18\v \x01(\x05R\tactiveMin\x12\x12\n" +
	"\x04exam\x18\f \x01(\bR\x04exam\"\x97\x01\n" +
	"\fCourseDetail\x12*\n" +
	"\x06course\x18\x01 \x01(\v2\x12.surgalt.v1.CourseR\x06course\x12-\n" +
	"\ateacher\x18\x02 \x01(\v2\x13.surgalt.v1.TeacherR\ateacher\x12,\n" +
	"\alessons\x18\x03 \x03(\v2\x12.surgalt.v1.LessonR\alessons\"K\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\x80\x02\n" +
	"\tSearchHit\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12-\n" +
	"\ateacher\x18\x03 \x01(\v2\x13.surgalt.v1.TeacherR\ateacher\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x18\n" +
	"\alessons\x18\x05 \x01(\x05R\alessons\x12!\n" +
	"\ffree_lessons\x18\x06 \x01(\x05R\vfreeLessons\x12\x14\n" +
	"\x05views\x18\a \x01(\x03R\x05views\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x14\n" +
	"\x05match\x18\t \x01(\tR\x05match\"\x98\x01\n" +
	"\x0eSearchResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.surgalt.v1.SearchHitR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\x12\x19\n" +
	"\bper_page\x18\x05 \x01(\x05R\aperPage\"\v\n" +
	"\tMeRequest\"\x88\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"c\n" +
	"\x13StartSessionRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"?\n" +
	"\tWatermark\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"\xf6\x01\n" +
	"\x06Policy\x12\x16\n" +
	"\x06camera\x18\x01 \x01(\tR\x06camera\x12\x19\n" +
	"\bping_sec\x18\x02 \x01(\x05R\apingSec\x12&\n" +
	"\x0fping_answer_sec\x18\x03 \x01(\x05R\rpingAnswerSec\x12\x19\n" +
	"\bidle_sec\x18\x04 \x01(\x05R\aidleSec\x12\x19\n" +
	"\bbeat_sec\x18\x05 \x01(\x05R\abeatSec\x12\x1d\n" +
	"\n" +
	"active_min\x18\x06 \x01(\x05R\tactiveMin\x12&\n" +
	"\x0factive_done_sec\x18\a \x01(\x05R\ractiveDoneSec\x12\x14\n" +
	"\x05owner\x18\b \x01(\bR\x05owner\"\x96\x01\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\twatermark\x18\x02 \x01(\v2\x15.surgalt.v1.WatermarkR\twatermark\x12*\n" +
	"\x06policy\x18\x03 \x01(\v2\x12.surgalt.v1.PolicyR\x06policy\"7\n" +
	"\tBeatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x9a\x02\n" +
	"\vBeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\x05R\x06active\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x05R\x04idle\x12\x12\n" +
	"\x04away\x18\x04 \x01(\x05R\x04away\x12\x1b\n" +
	"\tfocus_sum\x18\x05 \x01(\x01R\bfocusSum\x12\x17\n" +
	"\afocus_n\x18\x06 \x01(\x05R\x06focusN\x12\x16\n" +
	"\x06camera\x18\a \x01(\bR\x06camera\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\b \x01(\tR\tattemptId\x12\x10\n" +
	"\x03end\x18\t \x01(\tR\x03end\x12-\n" +
	"\x06events\x18\n" +
	" \x03(\v2\x15.surgalt.v1.BeatEventR\x06events\"F\n" +
	"\fBeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12&\n" +
	"\x0factive_done_sec\x18\x02 \x01(\x05R\ractiveDoneSec\"C\n" +
	"\x10AnalyticsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"\xa3\x05\n" +
	"\vStudentStat\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsessions\x18\x03 \x01(\x05R\bsessions\x12\x1b\n" +
	"\ttotal_sec\x18\x04 \x01(\x05R\btotalSec\x12\x1d\n" +
	"\n" +
	"active_sec\x18\x05 \x01(\x05R\tactiveSec\x12\x1d\n" +
	"\n" +
	"active_pct\x18\x06 \x01(\x05R\tactivePct\x12\x1c\n" +
	"\tattention\x18\a \x01(\x05R\tattention\x12\x1e\n" +
	"\n" +
	"violations\x18\b \x01(\x05R\n" +
	"violations\x12\x18\n" +
	"\alessons\x18\t \x01(\x05R\alessons\x12\x1b\n" +
	"\texam_best\x18\n" +
	" \x01(\x05R\bexamBest\x12#\n" +
	"\rquiz_accuracy\x18\v \x01(\x05R\fquizAccuracy\x12\x1d\n" +
	"\n" +
	"quiz_total\x18\f \x01(\x05R\tquizTotal\x12 \n" +
	"\vreflections\x18\r \x01(\x05R\vreflections\x12%\n" +
	"\x0evideo_coverage\x18\x0e \x01(\x05R\rvideoCoverage\x12\x1f\n" +
	"\vstreak_days\x18\x0f \x01(\x05R\n" +
	"streakDays\x12\x1f\n" +
	"\vlearn_score\x18\x10 \x01(\x05R\n" +
	"learnScore\x12\x12\n" +
	"\x04risk\x18\x11 \x01(\tR\x04risk\x12 \n" +
	"\flast_at_unix\x18\x12 \x01(\x03R\n" +
	"lastAtUnix\x12;\n" +
	"\x06counts\x18\x13 \x03(\v2#.surgalt.v1.StudentStat.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"c\n" +
	"\rDailyActivity\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x1d\n" +
	"\n" +
	"active_sec\x18\x02 \x01(\x05R\tactiveSec\x12!\n" +
	"\finactive_sec\x18\x03 \x01(\x05R\vinactiveSec\"\xb2\x02\n" +
	"\x11AnalyticsResponse\x123\n" +
	"\bstudents\x18\x01 \x03(\v2\x17.surgalt.v1.StudentStatR\bstudents\x12/\n" +
	"\x05daily\x18\x02 \x03(\v2\x19.surgalt.v1.DailyActivityR\x05daily\x12%\n" +
	"\x0etotal_students\x18\x03 \x01(\x05R\rtotalStudents\x12\x12\n" +
	"\x04live\x18\x04 \x01(\x05R\x04live\x12\x1d\n" +
	"\n" +
	"active_pct\x18\x05 \x01(\x05R\tactivePct\x12\x1c\n" +
	"\tattention\x18\x06 \x01(\x05R\tattention\x12\x1e\n" +
	"\n" +
	"violations\x18\a \x01(\x05R\n" +
	"violations\x12\x1f\n" +
	"\vlearn_score\x18\b \x01(\x05R\n" +
	"learnScore2\xa5\x04\n" +
	"\aSurgalt\x12G\n" +
	"\n" +
	"GetTeacher\x12\x1d.surgalt.v1.GetTeacherRequest\x1a\x1a.surgalt.v1.TeacherProfile\x12C\n" +
	"\tGetCourse\x12\x1c.surgalt.v1.GetCourseRequest\x1a\x18.surgalt.v1.CourseDetail\x12?\n" +
	"\x06Search\x12\x19.surgalt.v1.SearchRequest\x1a\x1a.surgalt.v1.SearchResponse\x12-\n" +
	"\x02Me\x12\x15.surgalt.v1.MeRequest\x1a\x10.surgalt.v1.User\x12Q\n" +
	"\fStartSession\x12\x1f.surgalt.v1.StartSessionRequest\x1a .surgalt.v1.StartSessionResponse\x12=\n" +
	"\x04Beat\x12\x17.surgalt.v1.BeatRequest\x1a\x18.surgalt.v1.BeatResponse(\x010\x01\x12=\n" +
	"\bBeatOnce\x12\x17.surgalt.v1.BeatRequest\x1a\x18.surgalt.v1.BeatResponse\x12K\n" +
	"\fGetAnalytics\x12\x1c.surgalt.v1.AnalyticsRequest\x1a\x1d.surgalt.v1.AnalyticsResponseB\x18Z\x16surgalt/internal/pb;pbb\x06proto3"

var (
	file_surgalt_v1_surgalt_proto_rawDescOnce sync.Once
	file_surgalt_v1_surgalt_proto_rawDescData []byte
)

func file_surgalt_v1_surgalt_proto_rawDescGZIP() []byte {
	file_surgalt_v1_surgalt_proto_rawDescOnce.Do(func() {
		file_surgalt_v1_surgalt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_surgalt_v1_surgalt_proto_rawDesc), len(file_surgalt_v1_surgalt_proto_rawDesc)))
	})
	return file_surgalt_v1_surgalt_proto_rawDescData
}

var file_surgalt_v1_surgalt_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_surgalt_v1_surgalt_proto_goTypes = []any{
	(*GetTeacherRequest)(nil),    // 0: surgalt.v1.GetTeacherRequest
	(*Link)(nil),                 // 1: surgalt.v1.Link
	(*Teacher)(nil),              // 2: surgalt.v1.Teacher
	(*Course)(nil),               // 3: surgalt.v1.Course
	(*TeacherProfile)(nil),       // 4: surgalt.v1.TeacherProfile
	(*GetCourseRequest)(nil),     // 5: surgalt.v1.GetCourseRequest
	(*Lesson)(nil),               // 6: surgalt.v1.Lesson
	(*CourseDetail)(nil),         // 7: surgalt.v1.CourseDetail
	(*SearchRequest)(nil),        // 8: surgalt.v1.SearchRequest
	(*SearchHit)(nil),            // 9: surgalt.v1.SearchHit
	(*SearchResponse)(nil),       // 10: surgalt.v1.SearchResponse
	(*MeRequest)(nil),            // 11: surgalt.v1.MeRequest
	(*User)(nil),                 // 12: surgalt.v1.User
	(*StartSessionRequest)(nil),  // 13: surgalt.v1.StartSessionRequest
	(*Watermark)(nil),            // 14: surgalt.v1.Watermark
	(*Policy)(nil),               // 15: surgalt.v1.Policy
	(*StartSessionResponse)(nil), // 16: surgalt.v1.StartSessionResponse
	(*BeatEvent)(nil),            // 17: surgalt.v1.BeatEvent
	(*BeatRequest)(nil),          // 18: surgalt.v1.BeatRequest
	(*BeatResponse)(nil),         // 19: surgalt.v1.BeatResponse
	(*AnalyticsRequest)(nil),     // 20: surgalt.v1.AnalyticsRequest
	(*StudentStat)(nil),          // 21: surgalt.v1.StudentStat
	(*DailyActivity)(nil),        // 22: surgalt.v1.DailyActivity
	(*AnalyticsResponse)(nil),    // 23: surgalt.v1.AnalyticsResponse
	nil,                          // 24: surgalt.v1.StudentStat.CountsEntry
}
var file_surgalt_v1_surgalt_proto_depIdxs = []int32{
	1,  // 0: surgalt.v1.Teacher.links:type_name -> surgalt.v1.Link
	2,  // 1: surgalt.v1.TeacherProfile.teacher:type_name -> surgalt.v1.Teacher
	3,  // 2: surgalt.v1.TeacherProfile.courses:type_name -> surgalt.v1.Course
	3,  // 3: surgalt.v1.CourseDetail.course:type_name -> surgalt.v1.Course
	2,  // 4: surgalt.v1.CourseDetail.teacher:type_name -> surgalt.v1.Teacher
	6,  // 5: surgalt.v1.CourseDetail.lessons:type_name -> surgalt.v1.Lesson
	2,  // 6: surgalt.v1.SearchHit.teacher:type_name -> surgalt.v1.Teacher
	9,  // 7: surgalt.v1.SearchResponse.items:type_name -> surgalt.v1.SearchHit
	14, // 8: surgalt.v1.StartSessionResponse.watermark:type_name -> surgalt.v1.Watermark
	15, // 9: surgalt.v1.StartSessionResponse.policy:type_name -> surgalt.v1.Policy
	17, // 10: surgalt.v1.BeatRequest.events:type_name -> surgalt.v1.BeatEvent
	24, // 11: surgalt.v1.StudentStat.counts:type_name -> surgalt.v1.StudentStat.CountsEntry
	21, // 12: surgalt.v1.AnalyticsResponse.students:type_name -> surgalt.v1.StudentStat
	22, // 13: surgalt.v1.AnalyticsResponse.daily:type_name -> surgalt.v1.DailyActivity
	0,  // 14: surgalt.v1.Surgalt.GetTeacher:input_type -> surgalt.v1.GetTeacherRequest
	5,  // 15: surgalt.v1.Surgalt.GetCourse:input_type -> surgalt.v1.GetCourseRequest
	8,  // 16: surgalt.v1.Surgalt.Search:input_type -> surgalt.v1.SearchRequest
	11, // 17: surgalt.v1.Surgalt.Me:input_type -> surgalt.v1.MeRequest
	13, // 18: surgalt.v1.Surgalt.StartSession:input_type -> surgalt.v1.StartSessionRequest
	18, // 19: surgalt.v1.Surgalt.Beat:input_type -> surgalt.v1.BeatRequest
	18, // 20: surgalt.v1.Surgalt.BeatOnce:input_type -> surgalt.v1.BeatRequest
	20, // 21: surgalt.v1.Surgalt.GetAnalytics:input_type -> surgalt.v1.AnalyticsRequest
	4,  // 22: surgalt.v1.Surgalt.GetTeacher:output_type -> surgalt.v1.TeacherProfile
	7,  // 23: surgalt.v1.Surgalt.GetCourse:output_type -> surgalt.v1.CourseDetail
	10, // 24: surgalt.v1.Surgalt.Search:output_type -> surgalt.v1.SearchResponse
	12, // 25: surgalt.v1.Surgalt.Me:output_type -> surgalt.v1.User
	16, // 26: surgalt.v1.Surgalt.StartSession:output_type -> surgalt.v1.StartSessionResponse
	19, // 27: surgalt.v1.Surgalt.Beat:output_type -> surgalt.v1.BeatResponse
	19, // 28: surgalt.v1.Surgalt.BeatOnce:output_type -> surgalt.v1.BeatResponse
	23, // 29: surgalt.v1.Surgalt.GetAnalytics:output_type -> surgalt.v1.AnalyticsResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_surgalt_v1_surgalt_proto_init() }
func file_surgalt_v1_surgalt_proto_init() {
	if File_surgalt_v1_surgalt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_surgalt_v1_surgalt_proto_rawDesc), len(file_surgalt_v1_surgalt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_surgalt_v1_surgalt_proto_goTypes,
		DependencyIndexes: file_surgalt_v1_surgalt_proto_depIdxs,
		MessageInfos:      file_surgalt_v1_surgalt_proto_msgTypes,
	}.Build()
	File_surgalt_v1_surgalt_proto = out.File
	file_surgalt_v1_surgalt_proto_goTypes = nil
	file_surgalt_v1_surgalt_proto_depIdxs = nil
}
