// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: surgalt/v1/surgalt.proto

// surgalt.mn — gRPC + Protobuf API.
// Нэг handler гурван протоколоор үйлчилнэ (Connect): gRPC (мобайл, сервис), gRPC-Web, Connect-JSON
// (хөтөч энгийн fetch-ээр: POST /surgalt.v1.Surgalt/<Method>, Content-Type: application/json).
// Токен: header "Authorization: Bearer <token>".
package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	pb "surgalt/internal/pb"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SurgaltName is the fully-qualified name of the Surgalt service.
	SurgaltName = "surgalt.v1.Surgalt"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SurgaltGetTeacherProcedure is the fully-qualified name of the Surgalt's GetTeacher RPC.
	SurgaltGetTeacherProcedure = "/surgalt.v1.Surgalt/GetTeacher"
	// SurgaltGetCourseProcedure is the fully-qualified name of the Surgalt's GetCourse RPC.
	SurgaltGetCourseProcedure = "/surgalt.v1.Surgalt/GetCourse"
	// SurgaltSearchProcedure is the fully-qualified name of the Surgalt's Search RPC.
	SurgaltSearchProcedure = "/surgalt.v1.Surgalt/Search"
	// SurgaltMeProcedure is the fully-qualified name of the Surgalt's Me RPC.
	SurgaltMeProcedure = "/surgalt.v1.Surgalt/Me"
	// SurgaltStartSessionProcedure is the fully-qualified name of the Surgalt's StartSession RPC.
	SurgaltStartSessionProcedure = "/surgalt.v1.Surgalt/StartSession"
	// SurgaltBeatProcedure is the fully-qualified name of the Surgalt's Beat RPC.
	SurgaltBeatProcedure = "/surgalt.v1.Surgalt/Beat"
	// SurgaltBeatOnceProcedure is the fully-qualified name of the Surgalt's BeatOnce RPC.
	SurgaltBeatOnceProcedure = "/surgalt.v1.Surgalt/BeatOnce"
	// SurgaltGetAnalyticsProcedure is the fully-qualified name of the Surgalt's GetAnalytics RPC.
	SurgaltGetAnalyticsProcedure = "/surgalt.v1.Surgalt/GetAnalytics"
)

// SurgaltClient is a client for the surgalt.v1.Surgalt service.
type SurgaltClient interface {
	// ---- нээлттэй ----
	GetTeacher(context.Context, *connect.Request[pb.GetTeacherRequest]) (*connect.Response[pb.TeacherProfile], error)
	GetCourse(context.Context, *connect.Request[pb.GetCourseRequest]) (*connect.Response[pb.CourseDetail], error)
	Search(context.Context, *connect.Request[pb.SearchRequest]) (*connect.Response[pb.SearchResponse], error)
	// ---- нэвтэрсэн хэрэглэгч ----
	Me(context.Context, *connect.Request[pb.MeRequest]) (*connect.Response[pb.User], error)
	// Хичээл үзэх идэвхийн сесс нээнэ (хяналтын бодлого, усан тэмдэг буцаана).
	StartSession(context.Context, *connect.Request[pb.StartSessionRequest]) (*connect.Response[pb.StartSessionResponse], error)
	// Клиент урсгалаар 15 секунд тутмын идэвхийн тайлан илгээнэ; сервер нийт идэвхтэй секундийг буцаана.
	Beat(context.Context) *connect.BidiStreamForClient[pb.BeatRequest, pb.BeatResponse]
	// Нэг удаагийн тайлан (хөтөч: fetch-ээр, урсгалгүй).
	BeatOnce(context.Context, *connect.Request[pb.BeatRequest]) (*connect.Response[pb.BeatResponse], error)
	// ---- багш ----
	GetAnalytics(context.Context, *connect.Request[pb.AnalyticsRequest]) (*connect.Response[pb.AnalyticsResponse], error)
}

// NewSurgaltClient constructs a client for the surgalt.v1.Surgalt service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSurgaltClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SurgaltClient {
	baseURL = strings.TrimRight(baseURL, "/")
	surgaltMethods := pb.File_surgalt_v1_surgalt_proto.Services().ByName("Surgalt").Methods()
	return &surgaltClient{
		getTeacher: connect.NewClient[pb.GetTeacherRequest, pb.TeacherProfile](
			httpClient,
			baseURL+SurgaltGetTeacherProcedure,
			connect.WithSchema(surgaltMethods.ByName("GetTeacher")),
			connect.WithClientOptions(opts...),
		),
		getCourse: connect.NewClient[pb.GetCourseRequest, pb.CourseDetail](
			httpClient,
			baseURL+SurgaltGetCourseProcedure,
			connect.WithSchema(surgaltMethods.ByName("GetCourse")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[pb.SearchRequest, pb.SearchResponse](
			httpClient,
			baseURL+SurgaltSearchProcedure,
			connect.WithSchema(surgaltMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		me: connect.NewClient[pb.MeRequest, pb.User](
			httpClient,
			baseURL+SurgaltMeProcedure,
			connect.WithSchema(surgaltMethods.ByName("Me")),
			connect.WithClientOptions(opts...),
		),
		startSession: connect.NewClient[pb.StartSessionRequest, pb.StartSessionResponse](
			httpClient,
			baseURL+SurgaltStartSessionProcedure,
			connect.WithSchema(surgaltMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		beat: connect.NewClient[pb.BeatRequest, pb.BeatResponse](
			httpClient,
			baseURL+SurgaltBeatProcedure,
			connect.WithSchema(surgaltMethods.ByName("Beat")),
			connect.WithClientOptions(opts...),
		),
		beatOnce: connect.NewClient[pb.BeatRequest, pb.BeatResponse](
			httpClient,
			baseURL+SurgaltBeatOnceProcedure,
			connect.WithSchema(surgaltMethods.ByName("BeatOnce")),
			connect.WithClientOptions(opts...),
		),
		getAnalytics: connect.NewClient[pb.AnalyticsRequest, pb.AnalyticsResponse](
			httpClient,
			baseURL+SurgaltGetAnalyticsProcedure,
			connect.WithSchema(surgaltMethods.ByName("GetAnalytics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// surgaltClient implements SurgaltClient.
type surgaltClient struct {
	getTeacher   *connect.Client[pb.GetTeacherRequest, pb.TeacherProfile]
	getCourse    *connect.Client[pb.GetCourseRequest, pb.CourseDetail]
	search       *connect.Client[pb.SearchRequest, pb.SearchResponse]
	me           *connect.Client[pb.MeRequest, pb.User]
	startSession *connect.Client[pb.StartSessionRequest, pb.StartSessionResponse]
	beat         *connect.Client[pb.BeatRequest, pb.BeatResponse]
	beatOnce     *connect.Client[pb.BeatRequest, pb.BeatResponse]
	getAnalytics *connect.Client[pb.AnalyticsRequest, pb.AnalyticsResponse]
}

// GetTeacher calls surgalt.v1.Surgalt.GetTeacher.
func (c *surgaltClient) GetTeacher(ctx context.Context, req *connect.Request[pb.GetTeacherRequest]) (*connect.Response[pb.TeacherProfile], error) {
	return c.getTeacher.CallUnary(ctx, req)
}

// GetCourse calls surgalt.v1.Surgalt.GetCourse.
func (c *surgaltClient) GetCourse(ctx context.Context, req *connect.Request[pb.GetCourseRequest]) (*connect.Response[pb.CourseDetail], error) {
	return c.getCourse.CallUnary(ctx, req)
}

// Search calls surgalt.v1.Surgalt.Search.
func (c *surgaltClient) Search(ctx context.Context, req *connect.Request[pb.SearchRequest]) (*connect.Response[pb.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// Me calls surgalt.v1.Surgalt.Me.
func (c *surgaltClient) Me(ctx context.Context, req *connect.Request[pb.MeRequest]) (*connect.Response[pb.User], error) {
	return c.me.CallUnary(ctx, req)
}

// StartSession calls surgalt.v1.Surgalt.StartSession.
func (c *surgaltClient) StartSession(ctx context.Context, req *connect.Request[pb.StartSessionRequest]) (*connect.Response[pb.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// Beat calls surgalt.v1.Surgalt.Beat.
func (c *surgaltClient) Beat(ctx context.Context) *connect.BidiStreamForClient[pb.BeatRequest, pb.BeatResponse] {
	return c.beat.CallBidiStream(ctx)
}

// BeatOnce calls surgalt.v1.Surgalt.BeatOnce.
func (c *surgaltClient) BeatOnce(ctx context.Context, req *connect.Request[pb.BeatRequest]) (*connect.Response[pb.BeatResponse], error) {
	return c.beatOnce.CallUnary(ctx, req)
}

// GetAnalytics calls surgalt.v1.Surgalt.GetAnalytics.
func (c *surgaltClient) GetAnalytics(ctx context.Context, req *connect.Request[pb.AnalyticsRequest]) (*connect.Response[pb.AnalyticsResponse], error) {
	return c.getAnalytics.CallUnary(ctx, req)
}

// SurgaltHandler is an implementation of the surgalt.v1.Surgalt service.
type SurgaltHandler interface {
	// ---- нээлттэй ----
	GetTeacher(context.Context, *connect.Request[pb.GetTeacherRequest]) (*connect.Response[pb.TeacherProfile], error)
	GetCourse(context.Context, *connect.Request[pb.GetCourseRequest]) (*connect.Response[pb.CourseDetail], error)
	Search(context.Context, *connect.Request[pb.SearchRequest]) (*connect.Response[pb.SearchResponse], error)
	// ---- нэвтэрсэн хэрэглэгч ----
	Me(context.Context, *connect.Request[pb.MeRequest]) (*connect.Response[pb.User], error)
	// Хичээл үзэх идэвхийн сесс нээнэ (хяналтын бодлого, усан тэмдэг буцаана).
	StartSession(context.Context, *connect.Request[pb.StartSessionRequest]) (*connect.Response[pb.StartSessionResponse], error)
	// Клиент урсгалаар 15 секунд тутмын идэвхийн тайлан илгээнэ; сервер нийт идэвхтэй секундийг буцаана.
	Beat(context.Context, *connect.BidiStream[pb.BeatRequest, pb.BeatResponse]) error
	// Нэг удаагийн тайлан (хөтөч: fetch-ээр, урсгалгүй).
	BeatOnce(context.Context, *connect.Request[pb.BeatRequest]) (*connect.Response[pb.BeatResponse], error)
	// ---- багш ----
	GetAnalytics(context.Context, *connect.Request[pb.AnalyticsRequest]) (*connect.Response[pb.AnalyticsResponse], error)
}

// NewSurgaltHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSurgaltHandler(svc SurgaltHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	surgaltMethods := pb.File_surgalt_v1_surgalt_proto.Services().ByName("Surgalt").Methods()
	surgaltGetTeacherHandler := connect.NewUnaryHandler(
		SurgaltGetTeacherProcedure,
		svc.GetTeacher,
		connect.WithSchema(surgaltMethods.ByName("GetTeacher")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltGetCourseHandler := connect.NewUnaryHandler(
		SurgaltGetCourseProcedure,
		svc.GetCourse,
		connect.WithSchema(surgaltMethods.ByName("GetCourse")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltSearchHandler := connect.NewUnaryHandler(
		SurgaltSearchProcedure,
		svc.Search,
		connect.WithSchema(surgaltMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltMeHandler := connect.NewUnaryHandler(
		SurgaltMeProcedure,
		svc.Me,
		connect.WithSchema(surgaltMethods.ByName("Me")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltStartSessionHandler := connect.NewUnaryHandler(
		SurgaltStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(surgaltMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltBeatHandler := connect.NewBidiStreamHandler(
		SurgaltBeatProcedure,
		svc.Beat,
		connect.WithSchema(surgaltMethods.ByName("Beat")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltBeatOnceHandler := connect.NewUnaryHandler(
		SurgaltBeatOnceProcedure,
		svc.BeatOnce,
		connect.WithSchema(surgaltMethods.ByName("BeatOnce")),
		connect.WithHandlerOptions(opts...),
	)
	surgaltGetAnalyticsHandler := connect.NewUnaryHandler(
		SurgaltGetAnalyticsProcedure,
		svc.GetAnalytics,
		connect.WithSchema(surgaltMethods.ByName("GetAnalytics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/surgalt.v1.Surgalt/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SurgaltGetTeacherProcedure:
			surgaltGetTeacherHandler.ServeHTTP(w, r)
		case SurgaltGetCourseProcedure:
			surgaltGetCourseHandler.ServeHTTP(w, r)
		case SurgaltSearchProcedure:
			surgaltSearchHandler.ServeHTTP(w, r)
		case SurgaltMeProcedure:
			surgaltMeHandler.ServeHTTP(w, r)
		case SurgaltStartSessionProcedure:
			surgaltStartSessionHandler.ServeHTTP(w, r)
		case SurgaltBeatProcedure:
			surgaltBeatHandler.ServeHTTP(w, r)
		case SurgaltBeatOnceProcedure:
			surgaltBeatOnceHandler.ServeHTTP(w, r)
		case SurgaltGetAnalyticsProcedure:
			surgaltGetAnalyticsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSurgaltHandler returns CodeUnimplemented from all methods.
type UnimplementedSurgaltHandler struct{}

func (UnimplementedSurgaltHandler) GetTeacher(context.Context, *connect.Request[pb.GetTeacherRequest]) (*connect.Response[pb.TeacherProfile], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.GetTeacher is not implemented"))
}

func (UnimplementedSurgaltHandler) GetCourse(context.Context, *connect.Request[pb.GetCourseRequest]) (*connect.Response[pb.CourseDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.GetCourse is not implemented"))
}

func (UnimplementedSurgaltHandler) Search(context.Context, *connect.Request[pb.SearchRequest]) (*connect.Response[pb.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.Search is not implemented"))
}

func (UnimplementedSurgaltHandler) Me(context.Context, *connect.Request[pb.MeRequest]) (*connect.Response[pb.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.Me is not implemented"))
}

func (UnimplementedSurgaltHandler) StartSession(context.Context, *connect.Request[pb.StartSessionRequest]) (*connect.Response[pb.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.StartSession is not implemented"))
}

func (UnimplementedSurgaltHandler) Beat(context.Context, *connect.BidiStream[pb.BeatRequest, pb.BeatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.Beat is not implemented"))
}

func (UnimplementedSurgaltHandler) BeatOnce(context.Context, *connect.Request[pb.BeatRequest]) (*connect.Response[pb.BeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.BeatOnce is not implemented"))
}

func (UnimplementedSurgaltHandler) GetAnalytics(context.Context, *connect.Request[pb.AnalyticsRequest]) (*connect.Response[pb.AnalyticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("surgalt.v1.Surgalt.GetAnalytics is not implemented"))
}
